import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Link from 'next/link';

import './globals.css';
import StoreProvider from './StoreProvider';
import styles from './page.module.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <Link href="/">Home</Link> | <Link href="/products">Products</Link>
        </header>
        <main className={styles.main}>
          <StoreProvider>{children}</StoreProvider>
        </main>
        <footer>Footer</footer>
      </body>
    </html>
  );
}
