import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import './globals.css';
import StoreProvider from './StoreProvider';
import styles from './page.module.css';
import NavLinks from './_components/navLinks/navLinks';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

const headerNavLinks = [
  { id: 1, name: 'Home', href: '/' },
  { id: 2, name: 'Products', href: '/products' }
];

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <NavLinks items={headerNavLinks} />
        </header>
        <main className={styles.main}>
          <StoreProvider>{children}</StoreProvider>
        </main>
        <footer>Footer</footer>
      </body>
    </html>
  );
}
